url: "http://www.efojs.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Denis Krasulin"

kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: false

# To avoid double livereload for Webpack
exclude: ['webpack', 'README.md']

# Jekyll-Atom
# for "new post" command
postFileType: ".html"
atom:
  postDirs:
    - _newsletters

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  categories:
     order:
       - fullstack.md
       - articles.md
       - experiments.md
       - apps.md
       - design.md
       - ideas.md
       - misc.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

excerpt_separator: <!-- more -->

frontMatter:
  - 'category:'
  - 'name:'
  - 'description:'
  - 'tech_stack:'
  - 'status:'
  - 'icon:'
  - 'nolink: true'
  - 'link:'
  - 'permalink:'
  - 'draft:'
